I'd like to interject for a moment...
davidscholberg/irkbot pull request #4
Opened 2017-04-10 03:03 UTC by dvdmuckle

Let me know if this is up to snuff.

2017-04-10 03:55 UTC, dvdmuckle commented
This isn't up to snuff. Will make up to snuff.

2017-04-11 01:11 UTC, davidscholberg requested changes
Just a few small changes.

2017-04-11 01:11 UTC, davidscholberg commented on lib/module/interject.go
> +	s := "interject <subject> - return a popular copypasta defaulting to our favorite operating system"
It should be `[subject]`, to indicate that the subject is optional.

Also, I'd change the description to: `give a pedantic rant about the proper way to refer to the given subject, defaulting to Linux if no subject given`. But that string is probably too long for one line, so please break it up using the `+` operator.

2017-04-11 01:11 UTC, davidscholberg commented on lib/module/interject.go
> +	}
you can simplify this a little by initializing `interMsg` to `Linux`, e.g.:

```go
interMsg := "Linux"
if len(in.MsgArgs[1:]) > 0 {
	interMsg = strings.Join(in.MsgArgs[1:], " ")
}
```

2017-04-11 01:11 UTC, davidscholberg commented on lib/module/interject.go
> +	msg := fmt.Sprintf("I'd just like to interject for a moment. What you're refering to as %s, is in fact, GNU/%s, or as I've recently taken to calling it, GNU plus %s.", interMsg, interMsg, interMsg)
This line is a bit too long. I generally try to keep the lines under 80 characters where practical, and it's certainly practical to do that with a long string if you use the `+` operator (of which there are example usages elsewhere in irkbot).

2017-04-11 01:22 UTC, davidscholberg commented on lib/module/interject.go
> +	msg := fmt.Sprintf("I'd just like to interject for a moment. What you're refering to as %s, is in fact, GNU/%s, or as I've recently taken to calling it, GNU plus %s.", interMsg, interMsg, interMsg)
Oh, also, I think that the `GNU/` should be changed to `GNU *slash*`, and `GNU plus` should be changed to `GNU *plus*`. I think that better fits the intended emphases.

2017-04-11 01:56 UTC, dvdmuckle commented
Shortened strings and cleaned up interMsg init, let me know if that's good.

2017-04-11 03:06 UTC, davidscholberg commented
Changes look good. Please fix the imports and squash your commits down to one.

2017-04-11 03:12 UTC, davidscholberg approved these changes

2017-04-11 03:45 UTC, merged